version: '3.8'

services:
  db:
    image: postgres:15
    container_name: securepay-db
    environment:
      POSTGRES_DB: securepay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - securepay-net

  app:
    build: .
    container_name: securepay-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/securepay
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - securepay-net

networks:
  securepay-net:
